crud1/urls.py
from django.conf.urls import url

from . import views

import crud1

app_name = 'crud1'

urlpatterns = [
	#ruta para eliminar
    	url(r'^hackenings/(?P<hackeningid>\d+)/delete/', crud1.views.delete_hackening, name='delete_hackening'),
	#listado
	url(r'^$', crud1.views.hackenings, name='list_hackenings'),
	#listado
	url(r'^hackenings/list', crud1.views.hackenings, name='list_hackenings'),
	#formulario para añadir
	url(r'^hackenings/add/', crud1.views.add_hackening, name='add_hackening'),
	#formulario para editar
	url(r'^hackenings/(?P<hackeningid>\d+)/', crud1.views.update_hackening, name='update_hackening')
]
	

polls/urls.py
from django.conf.urls import url

from . import views


app_name = 'polls'

urlpatterns = [
    # /polls/
    #url(r'^$', views.index, name='index'),
    url(r'^$', views.IndexView.as_view(), name='index'),
    # /polls/5/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    # /polls/5/results/
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    # /polls/5/vote/
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    # /polls/nueva/
    url(r'^nueva/$', views.CreateQuestionView.as_view(), name='nueva'),
    # /polls/nueva2/
    url(r'^manage/$', views.manage_questions, name='manage'),


]

sandboxprj/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from django.views.generic import TemplateView



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^polls/', include('polls.urls')),	
#    url(r'^$', include('polls.urls')),
    url(r'^crud1/', include('crud1.urls')),
    url(r'^$', TemplateView.as_view(template_name='start.html')),

]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('Fecha de publicación')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        now = timezone.now()
#        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = '¿Publicado recientemente?'

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

polls/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Question, Choice

from datetimewidget.widgets import DateTimeWidget, DateWidget, TimeWidget

#from bootstrap3_datetime.widgets import DateTimePicker

#class DatePicker(forms.DateInput):
#    template_name = 'date'

class QuestionForm(forms.ModelForm):
#    pub_date = forms.DateField(required=False, input_formats=['%d-%m-%Y'])
    class Meta:
        model = Question 
        fields = '__all__'
#        fields['pub_date'].widget.format = '%d/%m/%Y'
#        widgets = { 'pub_date': forms.DateInput(format=['%m/%d/%Y'], attrs={'class':'datepicker'} )} 
#        widgets = { 'pub_date': forms.DateInput(attrs={'class':'datepicker'} )} 
        widgets = { 'pub_date': forms.DateInput(attrs={'id':'id_pub_date'} )} 
#        pub_date = forms.DateTimeField(widget=DateTimePicker())
#        date_available = forms.DateField(widget=forms.widgets.DateInput(format="%d-%m-%Y"))
#        widgets = { 'pub_date': forms.DateInput(attrs={'class':'datepicker'},format = '%d/%m/%Y'), input_formats=('%d/%m/%Y',) }
#        fields['pub_date'] = forms.DateField(initial=pub_date.today(), widget=forms.DateInput(format = '%d/%m/%Y'), input_formats=('%d/%m/%Y',))
#        widgets = {
#            'pub_date': DateTimeWidget(attrs={'id':"id_pub_date"}, usel10n = True, bootstrap_version=3)
#        }

#    def __init__(self, *args, **kwargs):
#        super(QuestionForm, self).__init__(*args, **kwargs)
#        self.fields['pub_date'].widget.format = '%d/%m/%Y'

# at the same time, set the input format on the date field like you want it:
#        self.fields['pub_date'].input_formats = ['%d/%m/%Y']

polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.views.generic.edit import CreateView

from django import forms

import django, sys

from django.utils import timezone

from django.template import loader

from .models import Question, Choice

from django.forms import ModelForm, modelformset_factory, formset_factory

from .forms import QuestionForm


# Create your views here.

#def index(request):
#    latest_question_list = Question.objects.order_by('-pub_date')[:5]
#    template = loader.get_template('polls/index.html')
#    context = {
#        'latest_question_list':latest_question_list,
#    }
#    return render(request, 'polls/index.html', context)

#def detail(request, question_id):
#    question = get_object_or_404(Question, pk=question_id)
#    return render(request, 'polls/detail.html', {'question': question})

#def results(request, question_id):
#    question = get_object_or_404(Question, pk=question_id)
#    return render(request, 'polls/results.html', {'question': question})
class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
#        return Question.objects.order_by('-pub_date')[:5]
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "Seleccione alguna opción... no sea hptica...",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

class CreateQuestionView(CreateView):
#    fields = ('question_text',)
#    QuestionFormSet = modelformset_factory(Question, fields='__all__')
#    formset = QuestionFormSet()
#    QuestionFormSet = modelformset_factory(Question,fields=('__all__'))
    
#    if request.method == 'POST':
#        formset = QuestionFormSet(request.POST, request.FILES)
#        if formset.is_valid():
#            formset.save()
#            # do something.
#    else:
#    formset = QuestionFormSet()
#    return render(request, 'polls/nueva.html', {'formset': formset})

#    formset = QuestionFormSet()
    model = Question
    template_name = 'polls/nueva.html'
    form_class = QuestionForm


def manage_questions(request):

#        return Question.objects.order_by('-pub_date')[:5]
    preguntas = Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date').count()

    QuestionFormSet = formset_factory(QuestionForm, extra=preguntas)
    if request.method == 'POST':
        formset = QuestionFormSet(request.POST, request.FILES)
        if formset.is_valid():
            # do something with the formset.cleaned_data
            pass
    else:
        formset = QuestionFormSet()
    return render(request, 'polls/manage_questions.html', {'formset': formset})

polls/templates/polls/detail.html
{% extends 'polls/index.html' %}

{% block content %}

<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

{% endblock %}

polls/templates/polls/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang='es'>
    <head>
        <title>Es mejor una pregunta güevona que un güevón que no pregunta...</title>
<!--        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">-->

<!--	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script> -->

<!--	<script src="https://code.jquery.com/jquery-1.12.4.js" integrity="sha256-Qw82+bXyGq6MydymqBxNPYTaUXXq7c8v3CwiYwLLNXU=" crossorigin="anonymous"></script>-->

<!--	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>-->

<script src="https://code.jquery.com/jquery-3.1.0.js" integrity="sha256-slogkvB1K3VOkzAI8QITxV3VzpOnkeNVsKvtkYLMjfk=" crossorigin="anonymous"></script>

<!--	<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>-->

<script src="https://code.jquery.com/ui/1.12.0/jquery-ui.js" integrity="sha256-0YPKAwZP7Mp3ALMRVB2i8GXeEndvCq3eSl/WsAl1Ryk=" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.0/themes/smoothness/jquery-ui.css">


	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script> 


	<script src="{% static 'polls/moment.js' %} "></script>


<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/css/bootstrap-datetimepicker-standalone.css">
<link rel="" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/css/bootstrap-datetimepicker.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/js/bootstrap-datetimepicker.min.js"></script>


	<link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
        <link rel="stylesheet" href="{% static 'polls/style.css' %}">


<!--	<link rel="stylesheet" href="{% static 'polls/bootstrap/css/bootstrap.css' %} ">
	<script src="{% static 'polls/bootstrap/js/bootstrap.js' %} "></script>-->

<!--	<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.13.0/moment.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/3.1.4/js/bootstrap-datetimepicker.min.js"></script>-->



<!--	<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.13.0/moment.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/3.1.4/js/bootstrap-datetimepicker.min.js"></script>-->



<!--  <script>
  $(function() {
    $( ".datepicker" ).datepicker({
      changeMonth: true,
      changeYear: true,
      yearRange: "1900:2016",
      // You can put more options here.

    });
  });
  </script> -->

<!--<script>
    $( '#id_pub_date' ).datepicker();
</script>-->



    </head>

  <body>
        <div class="page-header">
            <h1><a href="/">GüevónAPP</a></h1>
        </div>
	<div id="content">
		{% block content %}
		<div class="post">
			{% if latest_question_list %}
			<ul>
				{% for question in latest_question_list %}
				<li>
					 <a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a>
				</li>
			{% endfor %}
			</ul>			
			{% else %}
				<p>No polls are available.</p>
			{% endif %}
		</div>
		<a href="{% url 'polls:nueva' %}">¿Qué otra güevonada desea sumercé preguntar?: </a>
		{% endblock %}
	</div>

<!--<script type="text/javascript">
            $(function () {
                $('#id_pub_date').datetimepicker();
            });
</script>-->

    </body>

<!--	<link rel="stylesheet" href="{% static 'polls/datetimepicker/jquery.datetimepicker.css' %} ">

	<script src="{% static 'polls/datetimepicker/jquery.js' %} "></script>
	<script src="{% static 'polls/datetimepicker/jquery.datetimepicker.full.min.js' %} "></script>-->

</html>

polls/templates/polls/manage_questions.html
{% extends 'polls/index.html' %}

{% block content %}

<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="" method="post">
	{% csrf_token %}
	{{ formset.management_form }}
<table >
	{% for form in formset %}
	{{ form }}
	{% endfor %}
</table>
<div class="form-group">
	<input type="submit" value="Guardar..." class="btn btn-primary"/>
</div>
</form>

<!--<script type="text/javascript">
            $(function () {
                $('#id_pub_date').datetimepicker();
            });
</script>-->
 <script>
  $(function() {
    $( "#id_pub_date" ).datepicker({
      changeMonth: true,
      changeYear: true,
      yearRange: "1900:2016",
      dateFormat: 'yy-mm-dd',
      // You can put more options here.

    });
  });
  </script>

{% endblock %}

polls/templates/polls/nueva.html
{% extends 'polls/index.html' %}

{% block content %}

<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="" method="post">
	{% csrf_token %}
<table >
	{{ form.as_table }}
</table>
<div class="form-group">
	<input type="submit" value="Guardar" class="btn btn-primary"/>
</div>
</form>

<!--<script type="text/javascript">
            $(function () {
                $('#id_pub_date').datetimepicker();
            });
</script>-->
 <script>
  $(function() {
    $( "#id_pub_date" ).datepicker({
      changeMonth: true,
      changeYear: true,
      yearRange: "1900:2016",
      dateFormat: 'yy-mm-dd',
      // You can put more options here.

    });
  });
  </script>

{% endblock %}

polls/templates/polls/results.html
{% extends 'polls/index.html' %}

{% block content %}


<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} => {{ choice.votes }} voto{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">¿Otra vez?</a>

{% endblock %}