crud1/urls.py
from django.conf.urls import url

from . import views

import crud1

app_name = 'crud1'

urlpatterns = [
	#ruta para eliminar
    	url(r'^hackenings/(?P<hackeningid>\d+)/delete/', crud1.views.delete_hackening, name='delete_hackening'),
	#listado
	url(r'^$', crud1.views.hackenings, name='list_hackenings'),
	#listado
	url(r'^hackenings/list', crud1.views.hackenings, name='list_hackenings'),
	#formulario para añadir
	url(r'^hackenings/add/', crud1.views.add_hackening, name='add_hackening'),
	#formulario para editar
	url(r'^hackenings/(?P<hackeningid>\d+)/', crud1.views.update_hackening, name='update_hackening')
]
	

sandboxprj/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from django.views.generic import TemplateView



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^polls/', include('polls.urls')),	
#    url(r'^$', include('polls.urls')),
    url(r'^crud1/', include('crud1.urls')),
    url(r'^$', TemplateView.as_view(template_name='start.html')),

]

crud1/models.py
from django.db import models

# Create your models here.
class Hackening(models.Model):
    title = models.CharField(max_length=100)
    url = models.CharField(max_length=150)
    content = models.TextField()

crud1/forms.py
from django.forms import ModelForm, Textarea, TextInput, URLInput
from .models import Hackening
 
class HackeningForm(ModelForm):
    class Meta:
        model = Hackening
        fields = ['title', 'url', 'content']
        widgets = {
            'content': Textarea(attrs={'class':'form-control', 'rows': 4}),
            'url': URLInput(attrs={'class':'form-control'}),
            'title': TextInput(attrs={'class':'form-control'}),
        }

crud1/views.py
from django.shortcuts import render, render_to_response, HttpResponseRedirect, get_object_or_404
from crud1.models import Hackening
from crud1.forms import HackeningForm
from django.contrib import messages


def hackenings(request):
    return render_to_response("hackenings.html", {"hackenings": Hackening.objects.all(), "messages": messages.get_messages(request)})

def add_hackening(request):
    form = HackeningForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, "Hackening guardado!")
            return HttpResponseRedirect("/crud1/hackenings/list/")

    return render(request, 'form_hackenings.html', {'form': form})

def update_hackening(request, hackeningid):
    instance = get_object_or_404(Hackening, id=hackeningid)
    form = HackeningForm(request.POST or None, instance=instance)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, "Hackening actualizado!")
            return HttpResponseRedirect("/crud1/hackenings/list/")

    return render(request, 'form_hackenings.html', {'form': form})

def delete_hackening(request, hackeningid):
    instance = get_object_or_404(Hackening, id=hackeningid)
    instance.delete()
    messages.add_message(request, messages.SUCCESS, "Hackening %s eliminado!" % hackeningid)
    return HttpResponseRedirect("/crud1/hackenings/list/")

crud1/templates/form_hackenings.html
{% extends "master.html" %}
{% block title %}
	Hackening
{% endblock %}

{% block content %}
<div class="row">
    <div class="panel panel-default">
        <div class="panel-body">
            <form action="" method="post">{% csrf_token %}
                {{ form.as_p }}
            <input type="submit" class="btn btn-block btn-success" value="Submit">
        </form>
        </div>
    </div>
</div>
{% endblock %}
<!--finaliza el bloque content-->
<!--heredamos el bloque footer-->
{% block footer %}
	 <div class="navbar navbar-inverse navbar-fixed-bottom">
	 	<center style="padding-top: 12px">
	 		<small style="color: #fff">Footer Form</small>
	    </center>
	</div>
{% endblock %}
<!--finaliza el bloque footer-->

crud1/templates/hackenings.html
{% extends "master.html" %}
<!--heredamos el bloque title-->
{% block title %}
	<!--establecemos el titulo en el bloque title-->
	Listado de Hackenings
{% endblock %}
<!--finaliza el bloque title-->

<!--heredamos el bloque content-->
{% block content %}
<div class="row">
    <!-- mostramos los mensajes flash -->
    {% if messages %}
        <div class="alert alert-success">
            {% for message in messages %}
                {{ message }}
            {% endfor %}
        </div>
    {% endif %}
    <div class="panel panel-default">
        <div class="panel-body">
            {% if hackenings|length > 0 %}
                <h2>HACKENINGS</h2>
                {% for hackening in hackenings %}
                     <div class="col-md-12" style="margin-bottom: 6px">
                        <div class="col-md-8">
                            Title: {{ hackening.title }}, Url: {{ hackening.url }}, Content: {{ hackening.content }}
                         </div>
                         <div class="col-md-4">
                             <a href="{% url 'crud1:update_hackening' hackening.id %}" class="btn btn-success">Actualizar</a>
                              <a href="{% url 'crud1:delete_hackening' hackening.id %}" class="btn btn-danger">Eliminar</a>
                         </div>
                     </div>
                {% endfor %}
            {% else %}
                <p>No hay hackenings</p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}
<!--finaliza el bloque content-->
<!--heredamos el bloque footer-->
{% block footer %}
	 <div class="navbar navbar-inverse navbar-fixed-bottom">
	 	<div class="text-center" style="padding-top: 12px">
	 		<small style="color: #fff">Footer Hackening List</small>
	    </div>
	</div>
{% endblock %}
<!--finaliza el bloque footer-->

crud1/templates/master.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <!-- bloque de contenido para el título-->
    <title>Crud con Python y Django | {% block title %}Página principal{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
</head>
<body>
    <div id="header">
        <!-- bloque de contenido para el menú-->
        {% block header %}
            <nav class="navbar navbar-inverse">
                <div class="navbar-header">
                    <a class="navbar-brand" href="{% url 'crud1:list_hackenings' %}">Hackenings</a>
                    <a class="navbar-brand" href="{% url 'crud1:add_hackening' %}">Nuevo Hackening</a>
                </div>
            </nav>
        {% endblock %}
    </div>
    <div class="container">
        <!-- bloque de contenido para el contenido de la página-->
        {% block content %}

        {% endblock %}
    </div>

    <footer class="footer">
        <!-- bloque de contenido para el footer-->
        {% block footer %}{% endblock %}
    </footer>
</body>
</html>